# Generated by Django 5.2.1 on 2025-05-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type', models.CharField(max_length=50)),
                ('signal_status', models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], default='red', max_length=10)),
                ('traffic_condition', models.CharField(choices=[('clear', 'Clear'), ('congested', 'Congested')], default='clear', max_length=10)),
            ],
        ),
    ]
