# Generated by Django 5.2.1 on 2025-05-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signalStatus', models.CharField(max_length=10)),
                ('trafficCondition', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='Scenario',
        ),
    ]
