# Generated by Django 5.2.1 on 2025-05-24 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_signal_delete_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signal',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='signal',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='signal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='signalStatus',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='signal',
            name='trafficCondition',
            field=models.CharField(max_length=100),
        ),
    ]
