# Generated by Django 5.2.1 on 2025-05-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_signal_created_at_signal_latitude_signal_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='signal',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='signal',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='signal',
            name='trafficCondition',
            field=models.CharField(max_length=50),
        ),
    ]
